channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - notebook
  - pip:
    - tensorboard
    - pytorch-lightning
    - torchmetrics